### ISSUE TITLE
highestSequenceNo should be kept on message deletion 

### ISSUE THREAD

**Issue by eshepelyuk** [dnvriend/akka-persistence-inmemory#13]
With `AKKA 2.4.1` release there comes a clarification about `highestSeqenceNo` behavior on message deletion. This issue akka/akka#18559 adds tests to plugin TCK that will enforce maintaining `highestSequenceNo` for persistenceId after message deletion or journal cleanup.

Currently `akka-persistence-inmemory` doesn't maintain `highestSequenceNo`, and it is reset on journal cleanup. This should be fixed for future compatibility with `AKKA 2.4.1`

@dnvriend I'd like to pick up and fix the issue if you have no objections.

**Comment by dnvriend** [comment]
I have read the [issue](https://github.com/akka/akka/issues/18559). [Martin Krasser's Cassandra plugin](https://github.com/krasserm/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraRecovery.scala#L28) uses a metadata model that stores the `deleted_to` sequence number for the `persistence_id`, so that the sequence number will never be rewind to zero. The case [as explained by Patrik Nordwall](https://github.com/akka/akka/issues/18559#issuecomment-143796714) would be solved when the journal saves the state into the metadata model. This way, sequence numbers will always be incremented, even after deletion. 

No problem if you want to fix the issue :)

**Comment by dnvriend** [comment]
Fixed with release v1.1.5
