### ISSUE TITLE
Journal doesn't send any events unless a delay is added

### ISSUE THREAD

**Issue by ale64bit** [dnvriend/akka-persistence-inmemory#24]
I'm using inmem-journal and I have come frequently to an scenario where some tests fail unless I add some delay right after the journal was issued a query. Probably I'm missing something, but anyway I wrote a small gist to show the point: https://gist.github.com/ale64bit/f3a452b501b9bc8d31ba

The commented delay causes the test to pass. Otherwise I get a timeout waiting for `EventEnvelope`. I'm using Akka 2.4.2 with Scala 2.11.7.

Thanks!

**Comment by dnvriend** [comment]
This case looks like a sequence problem. The following is assumed:
1. Events are read from the journal
2. An async query has been subscribed
3. A message has been persisted,
4. The message will be sent to the Testprobe

But the following happens:
1. Events are read from the journal
2. Request for a query subscription has been posted to Akka
3. A message has been persisted
4. The query subscriber has been added  to the subscription list
5. The event will never be forwarded to the subscriber because none was registered at the time.

Just a little delay (50millis seems to work on my LT) gives akka enough time to handle the message and add the subscriber to the subscription list.

**Comment by ale64bit** [comment]
So this can actually happen in a production system and a view can end up receiving no events? What could be modified in the view actor to take into account this sort of race condition?

**Comment by ale64bit** [comment]
For example, if the view is removed from the test and you simplify it as follows:
```
import system.dispatcher

  "FooView" should "receive the events in the journal eventually" in {
    val consumer = TestProbe()

    Future {
      // if this first query is removed, the test passes as well (note that messages are ignored)
      readJournal
        .currentEventsByPersistenceId("foo", 0L, Long.MaxValue)
        .runWith(Sink.ignore)
      readJournal
        .eventsByPersistenceId("foo", 0L, Long.MaxValue)
        .runWith(Sink.actorRef(consumer.ref, "done"))
    }

    // test passes if the delay is uncommented
    // Thread sleep 100

    val fooActor = system.actorOf(Props(new FooActor), "foo")
    fooActor ! "foo"

    consumer.expectMsg(10 seconds, EventEnvelope(1l, "foo", 1l, "bar"))
  }
```
The test passes if the first query is removed, the timeout is uncommented or the Future block is removed.

**Comment by dnvriend** [comment]
I think that the design should take in account that things (can and will) happen out of order. When we wish to subscribe to events, we must enforce that the subscriptions happens before we write to the journal. So, the the design of the application must handle this sequence. When the subscriptions are placed in a Future concept, the order of things are not fixed, and as such, it is non-deterministic. The design should take the non-deterministic nature of asynchronous messaging into account.

**Comment by ale64bit** [comment]
I totally agree with you; the design should definitely take into account such non-deterministic scenarios. But it just feels weird that when I issue this query
```scala
readJournal.eventsByPersistenceId("foo", 0L, Long.MaxValue).runWith(Sink.actorRef(someActorRef, "done"))
```
I may be getting an empty stream due to a race condition. I would expect it to emit the events, independently of when/where/how the events were persisted. How can I differ between a genuinely empty stream and a "broken" one that looks empty?

Btw, thanks a lot for the plugin! :) It works great.

**Comment by dnvriend** [comment]
This is a very interesting question. I have talked about it with my peers and there is a good amount of discussion about it :) Should the plugin guarantee / handle the unlimited amount of use cases eg. by implementing a polling mechanism on the journal, or should the plugin user handle the sequence of events? Both have pros and cons. With polling, the amount of consumers could overload the journal (without any management). When I find the time I will look how the reference implementation (the LevelDB journal) does things..

**Comment by dnvriend** [comment]
### Akka Persistence Query Consumer Refactor
The akka persistence query api is based upon a producer-push approach in where persisted events will be pushed downstream to any subscribers of the log. This rather naive approach has as a side effect that there has to be some kind of subscription management in akka-persistence. At the moment there is none available in akka persistence and so the current design of akka-perisistence-inmemory must change.

### Looking at other log architectures
There are other log architectures, for example [Apache Kafka](http://kafka.apache.org/), that use a clean separation of concerns [design](https://kafka.apache.org/08/design.html) that consists of one or more producers that write to a log, the broker itself that manages the log, and one or more consumers that read from the log. This separation makes it possible to look at the problem of each component in isolation and create a design that focuses on the single responsibility that it has.

So when looking only at the consumer of the kafka log, [the consumer](https://kafka.apache.org/08/design.html#theconsumer)
has the following responsibilities:
 
 * pulling data from the broker by issuing 'fetch' requests to the brokers what to consume,
 * specifying its position in the log with each request,
 * handing the response, which consists of a chunk of data beginning from the log position,
 * issuing the maximum number of messages the client can handle by means of a back pressure mechanism
 
### Refactoring the akka persistence in-memory query clients
When looking at the design of the Akka Persistence, the client api are also fully separate of the producer 
of the log. When we copy the design of Kafka, the following changes to the design to the akka persistence in-memory query api clients can be made:

 * active clients that `pull` from the broker by issuing `fetch` requests,
 * handling the response that conform to the [reactive streams](http://www.reactive-streams.org/) specification,
 * specifying `the position` in the log with each request with a `maximum number of messages`,
 * delivering the messages to any subscribers of the stream.
 
This design places the responsibility of consuming the log and making sure that messages are send to any waiting subscribers of the the log solely on the consumer API and decouples the producer from the consumer. The producer (here akka-persistence) must be changed because it does not have to take consumers into account. It has a single responsibility, batch writing messages to the log. 

This design change has an impact to the design and will be reflected in a change to the source code.

**Comment by dnvriend** [comment]
Should work now with v1.3.0
